### ISSUE TITLE
Missing 10.5-inch iPad Pro

### ISSUE THREAD

**Issue by ElectroBuddha** [anatoliyv/AssistantKit#12]
Hi,
It seems there is only detection for 12.9 inch iPad Pro, but no detection for 10.5-inch iPad Pro (screen resolution: 2224 × 1668 px)

**Comment by vsg24** [comment]
+1, Why is there no iPad 10.5?

**Comment by victorlobe** [comment]
bump

**Comment by heysaik** [comment]
Why is there no iPad 11?
