### ISSUE TITLE
iPhone9,3 is unknown.  Crash in "osVersion"

### ISSUE THREAD

**Issue by timothycosta** [anatoliyv/AssistantKit#8]
Just installed AssistantKit and it looks very interesting.  My iPhone 7 isn't detected, so I've created a pull request here: https://github.com/anatoliyv/AssistantKit/pull/7

Also, `osVersion` crashes because of `Float(UIDevice.current.systemVersion)!`.  `UIDevice.current.systemVersion` returns `10.3.1` which can't be converted.  I don't know what the best way to handle that is.

**Comment by anatoliyv** [comment]
Crash fixed by removing `osVersion`. I think it's useless property: no way to convert "10.2.3" to Float imo. Thank you for your pull request!
